#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all, non_snake_case)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod GasHog;
pub mod Counter;
pub mod CowProtocolToken;
pub mod NonStandardERC20Balances;
pub mod RemoteERC20Balances;
